### PR TITLE
Add support for update or insert

### PR DESCRIPTION
**Pull request by Jdochoa**
Add support for update or insert #94 

Update Insert

### CODE REVIEW

**Comment by arvanus** [comment]
@Jdochoa could you take a look that it's repeating the `insert or update` SQL N times, where `N=total records - current position`
Also if you select more than 1 row, it gets strange

**Comment by arvanus** [comment]
Suggestion, remove the matching part or verify if the selected part has the PK part, if not them omit the patch part. But be aware that you could use another fields to match, or even another unique key (so it's simpler to remove/ignore the matching part)

**Comment by Jdochoa** [comment]
Hi @arvanus 
Please review my last commit en dev branch.

./jo

**Comment by arvanus** [comment]
working fine on dev!

**Pull request merged**
