### PR TITLE
Cleaned up all wx depreciated warnings

### PR DESCRIPTION
**Pull request by blumf**

### CODE REVIEW

**Comment by blumf** [comment]
Check is failing because it's building against wxWidgets 3.0 instead of 3.1, think we need to bump that requirement up on the build test

**Comment by mariuz** [comment]
maybe we should do some checks for wx version #if wxCHECK_VERSION(3, 1, 1)  StartStyling(0) else ... 

similar to 
https://github.com/eranif/codelite/issues/2292
https://github.com/eranif/codelite/commit/92ed90e07774dfc8556bee02c66120eed4938a40

**Comment by mariuz** [comment]
In debian/ubuntu we are stuck with wxwidgets 3.0 https://packages.debian.org/source/sid/wxwidgets3.0 so we need to backward compatible patches

**Comment by blumf** [comment]
Yeah, I'm think we should roll back the problem 'StartStyling' call changes for now. It doesn't hurt anything on wx3.1, just build noise.

**Comment by mariuz** [comment]
just ifdef and maybe later we can build for both 3.1 and 3.0  something similar to https://wiki.codelite.org/pmwiki.php/Main/WxWidgets31Binaries

**Comment by blumf** [comment]
Seems like wxWidgets is aiming for a new stable 3.2 release [by the end of the year](https://trac.wxwidgets.org/wiki/Roadmap), at which point the linux distros should pick it up. Might be better to leave the old 3.0 'StartStyling' calls in place until then, rather than leaving ifdefs to be forgotten about.

**Pull request merged**
